// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0--rc2
// source: proto/v1/distfs.proto

package distfspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DistFS_Put_FullMethodName  = "/distfs.v1.DistFS/Put"
	DistFS_Get_FullMethodName  = "/distfs.v1.DistFS/Get"
	DistFS_List_FullMethodName = "/distfs.v1.DistFS/List"
)

// DistFSClient is the client API for DistFS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DistFS Service which provides a remote file storage service.
type DistFSClient interface {
	// Put streams a file to the server. The first message contains metadata,
	// subsequent messages contain only chunk_data.
	Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutRequest, PutResponse], error)
	// Get streams a file back to the client.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error)
	// List returns all stored files with metadata.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type distFSClient struct {
	cc grpc.ClientConnInterface
}

func NewDistFSClient(cc grpc.ClientConnInterface) DistFSClient {
	return &distFSClient{cc}
}

func (c *distFSClient) Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutRequest, PutResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DistFS_ServiceDesc.Streams[0], DistFS_Put_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutRequest, PutResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DistFS_PutClient = grpc.ClientStreamingClient[PutRequest, PutResponse]

func (c *distFSClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DistFS_ServiceDesc.Streams[1], DistFS_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, GetResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DistFS_GetClient = grpc.ServerStreamingClient[GetResponse]

func (c *distFSClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, DistFS_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistFSServer is the server API for DistFS service.
// All implementations must embed UnimplementedDistFSServer
// for forward compatibility.
//
// DistFS Service which provides a remote file storage service.
type DistFSServer interface {
	// Put streams a file to the server. The first message contains metadata,
	// subsequent messages contain only chunk_data.
	Put(grpc.ClientStreamingServer[PutRequest, PutResponse]) error
	// Get streams a file back to the client.
	Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error
	// List returns all stored files with metadata.
	List(context.Context, *ListRequest) (*ListResponse, error)
	mustEmbedUnimplementedDistFSServer()
}

// UnimplementedDistFSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDistFSServer struct{}

func (UnimplementedDistFSServer) Put(grpc.ClientStreamingServer[PutRequest, PutResponse]) error {
	return status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedDistFSServer) Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error {
	return status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDistFSServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDistFSServer) mustEmbedUnimplementedDistFSServer() {}
func (UnimplementedDistFSServer) testEmbeddedByValue()                {}

// UnsafeDistFSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistFSServer will
// result in compilation errors.
type UnsafeDistFSServer interface {
	mustEmbedUnimplementedDistFSServer()
}

func RegisterDistFSServer(s grpc.ServiceRegistrar, srv DistFSServer) {
	// If the following call panics, it indicates UnimplementedDistFSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DistFS_ServiceDesc, srv)
}

func _DistFS_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DistFSServer).Put(&grpc.GenericServerStream[PutRequest, PutResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DistFS_PutServer = grpc.ClientStreamingServer[PutRequest, PutResponse]

func _DistFS_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DistFSServer).Get(m, &grpc.GenericServerStream[GetRequest, GetResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DistFS_GetServer = grpc.ServerStreamingServer[GetResponse]

func _DistFS_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistFSServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistFS_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistFSServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DistFS_ServiceDesc is the grpc.ServiceDesc for DistFS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistFS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distfs.v1.DistFS",
	HandlerType: (*DistFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _DistFS_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _DistFS_Put_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _DistFS_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/v1/distfs.proto",
}
