// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc2
// source: proto/v1/distfs.proto

package distfspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// request: client -> server
type PutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PutRequest_Info
	//	*PutRequest_ChunkData
	Payload       isPutRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_v1_distfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_distfs_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetPayload() isPutRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PutRequest) GetInfo() *FileInfo {
	if x != nil {
		if x, ok := x.Payload.(*PutRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *PutRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*PutRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isPutRequest_Payload interface {
	isPutRequest_Payload()
}

type PutRequest_Info struct {
	// First message only: file metadata.
	// size_bytes is an advisory hint used by the server only for an upfront
	// capacity check; the stored size is the actual number of bytes received.
	// last_modified is stored verbatim and echoed back in ListResponse; the
	// server does not use it for ordering, staleness, or validation.
	Info *FileInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type PutRequest_ChunkData struct {
	// Subsequent messages: raw file bytes, up to 256 KB per chunk
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*PutRequest_Info) isPutRequest_Payload() {}

func (*PutRequest_ChunkData) isPutRequest_Payload() {}

// response: server -> client
type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"` // number of bytes server wrote
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_v1_distfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_distfs_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

// request: client -> server
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // remote path, e.g. "jobs/resume"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_v1_distfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_distfs_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// response: server -> client
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each response is apart of a stream
	ChunkData     []byte `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_v1_distfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_distfs_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

// request: client -> server
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        *string                `protobuf:"bytes,1,opt,name=prefix,proto3,oneof" json:"prefix,omitempty"` // remote path to list files
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_v1_distfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_distfs_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequest) GetPrefix() string {
	if x != nil && x.Prefix != nil {
		return *x.Prefix
	}
	return ""
}

// response: server -> client
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"` // List of file metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_v1_distfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_distfs_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

// File metadata
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                     // remote path
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`         // total size of file
	LastModified  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"` // time of last modification in UTC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_v1_distfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_distfs_proto_rawDescGZIP(), []int{6}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileInfo) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

var File_proto_v1_distfs_proto protoreflect.FileDescriptor

const file_proto_v1_distfs_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/distfs.proto\x12\tdistfs.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n" +
	"\n" +
	"PutRequest\x12)\n" +
	"\x04info\x18\x01 \x01(\v2\x13.distfs.v1.FileInfoH\x00R\x04info\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\t\n" +
	"\apayload\"2\n" +
	"\vPutResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\vGetResponse\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x01 \x01(\fR\tchunkData\"5\n" +
	"\vListRequest\x12\x1b\n" +
	"\x06prefix\x18\x01 \x01(\tH\x00R\x06prefix\x88\x01\x01B\t\n" +
	"\a_prefix\"9\n" +
	"\fListResponse\x12)\n" +
	"\x05files\x18\x01 \x03(\v2\x13.distfs.v1.FileInfoR\x05files\"~\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12?\n" +
	"\rlast_modified\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified2\xb1\x01\n" +
	"\x06DistFS\x126\n" +
	"\x03Put\x12\x15.distfs.v1.PutRequest\x1a\x16.distfs.v1.PutResponse(\x01\x126\n" +
	"\x03Get\x12\x15.distfs.v1.GetRequest\x1a\x16.distfs.v1.GetResponse0\x01\x127\n" +
	"\x04List\x12\x16.distfs.v1.ListRequest\x1a\x17.distfs.v1.ListResponseB.Z,github.com/kyukibug/distfs/proto/v1;distfspbb\x06proto3"

var (
	file_proto_v1_distfs_proto_rawDescOnce sync.Once
	file_proto_v1_distfs_proto_rawDescData []byte
)

func file_proto_v1_distfs_proto_rawDescGZIP() []byte {
	file_proto_v1_distfs_proto_rawDescOnce.Do(func() {
		file_proto_v1_distfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_distfs_proto_rawDesc), len(file_proto_v1_distfs_proto_rawDesc)))
	})
	return file_proto_v1_distfs_proto_rawDescData
}

var file_proto_v1_distfs_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_v1_distfs_proto_goTypes = []any{
	(*PutRequest)(nil),            // 0: distfs.v1.PutRequest
	(*PutResponse)(nil),           // 1: distfs.v1.PutResponse
	(*GetRequest)(nil),            // 2: distfs.v1.GetRequest
	(*GetResponse)(nil),           // 3: distfs.v1.GetResponse
	(*ListRequest)(nil),           // 4: distfs.v1.ListRequest
	(*ListResponse)(nil),          // 5: distfs.v1.ListResponse
	(*FileInfo)(nil),              // 6: distfs.v1.FileInfo
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_v1_distfs_proto_depIdxs = []int32{
	6, // 0: distfs.v1.PutRequest.info:type_name -> distfs.v1.FileInfo
	6, // 1: distfs.v1.ListResponse.files:type_name -> distfs.v1.FileInfo
	7, // 2: distfs.v1.FileInfo.last_modified:type_name -> google.protobuf.Timestamp
	0, // 3: distfs.v1.DistFS.Put:input_type -> distfs.v1.PutRequest
	2, // 4: distfs.v1.DistFS.Get:input_type -> distfs.v1.GetRequest
	4, // 5: distfs.v1.DistFS.List:input_type -> distfs.v1.ListRequest
	1, // 6: distfs.v1.DistFS.Put:output_type -> distfs.v1.PutResponse
	3, // 7: distfs.v1.DistFS.Get:output_type -> distfs.v1.GetResponse
	5, // 8: distfs.v1.DistFS.List:output_type -> distfs.v1.ListResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_distfs_proto_init() }
func file_proto_v1_distfs_proto_init() {
	if File_proto_v1_distfs_proto != nil {
		return
	}
	file_proto_v1_distfs_proto_msgTypes[0].OneofWrappers = []any{
		(*PutRequest_Info)(nil),
		(*PutRequest_ChunkData)(nil),
	}
	file_proto_v1_distfs_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_distfs_proto_rawDesc), len(file_proto_v1_distfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_distfs_proto_goTypes,
		DependencyIndexes: file_proto_v1_distfs_proto_depIdxs,
		MessageInfos:      file_proto_v1_distfs_proto_msgTypes,
	}.Build()
	File_proto_v1_distfs_proto = out.File
	file_proto_v1_distfs_proto_goTypes = nil
	file_proto_v1_distfs_proto_depIdxs = nil
}
